// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dijkstraSparseMatrix
Rcpp::NumericVector dijkstraSparseMatrix(Rcpp::S4 dgCMatrix, Rcpp::String startNode);
RcppExport SEXP _Dijkstra_dijkstraSparseMatrix(SEXP dgCMatrixSEXP, SEXP startNodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type dgCMatrix(dgCMatrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type startNode(startNodeSEXP);
    rcpp_result_gen = Rcpp::wrap(dijkstraSparseMatrix(dgCMatrix, startNode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Dijkstra_dijkstraSparseMatrix", (DL_FUNC) &_Dijkstra_dijkstraSparseMatrix, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Dijkstra(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
