# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Dijkstra algorithm implementation.
#' This is the final implementation of the Dikstra algorithm by using a
#' min-priority queue.
#' @param graph a vector of Nodes, representing the graph structure
#' @param startNode the starting node which we are interested in calculating
#'         the shortest paths
NULL

#' Dijkstra algorithm implementation - input a SparseMatrix
#' @param dgCMatrix the Graph structure representation as output from
#'         as_adj(graph, attr = "weight")
#' @param startNode the label of the starting node which we are interested in +
#'         calculating the shortest paths
dijkstraSparseMatrix <- function(dgCMatrix, startNode) {
    .Call(`_Dijkstra_dijkstraSparseMatrix`, dgCMatrix, startNode)
}

