# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Dijkstra algorithm implementation
#' @param mat the Graph structure representation as output from as_edgelist(G)
#' @param weights a vector containing the weights for each edge(each line) of
#'       the edgelist matrix
dijkstra <- function(mat, weights) {
    .Call(`_Dijkstra_dijkstra`, mat, weights)
}

