# Custom workflow implemented in the FabrizioSandri/Gsoc-RcppDeepState-Medium repository
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: custom-check

jobs:

  custom_test:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v2

      - name: Setup R environment and test cities graph 
        uses: FabrizioSandri/Gsoc-RcppDeepState-Medium@main
        with:
          source_node: "Rome"
      
